### ISSUE TITLE
Explore adding Cesium.js to the map for 3D visualizations

### ISSUE THREAD

**Issue by lambdatronic** [pyregence/pyregence#159]

**Comment by aliceliquori** [comment]
Commenting here - modern mapbox uses webgl afaik, and supports shaders and actual geometry as a consequence. It could be a smaller lift if much of the interface is the same outside of that. No issue with cesium but worth mentioning, noting that I am not an authority on either.

**Comment by lambdatronic** [comment]
@aliceliquori I'm not sure how this came up again. This PR has been closed since March 2021.
